# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [37]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [41]:
data = pd.read_csv("Ciudades2014Limpio.csv")

In [57]:
feature_cols = ["Apertura de un negocio", "Densidad poblacional", "Salario mensual para trabajadores de tiempo completo", "Crédito a las empresas", "Diversificación económica", "Acceso a servicios financieros", "Inversión extranjera directa neta", "Ciudad fronteriza o portuaria", "Empresas", "Centros de investigación", "Patentes", "Superficie Urbana"]

In [58]:
X = data[feature_cols]
Y = data["PIB"]

In [59]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 3, step=1)
selector = selector.fit(X,Y)

In [60]:
selector.support_

array([False, False,  True, False,  True, False, False, False, False,
       False, False,  True])

In [61]:
selector.ranking_

array([10,  7,  1,  3,  1,  8,  2,  9,  5,  6,  4,  1])

In [62]:
from sklearn.linear_model import LinearRegression

In [63]:
X_pred = X[["Salario mensual para trabajadores de tiempo completo", "Diversificación económica", "Superficie Urbana"]]

In [64]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [65]:
lm.intercept_

21538763.283878088

In [66]:
lm.coef_

array([  60973.09664701, -953812.30990031, 2133709.45028103])

In [67]:
lm.score(X_pred, Y)

0.9275236373777893